//
//  Streamer.swift
//  ChessStreamers
//
//  Created by Sebastian Strus on 2021-12-10.
//

import Foundation

// TODO: Use Model generated by Core Data instead
struct Streamer: Codable {
    
    let username: String
    let avatarUrl: String
    let url: String
    let isLive: Bool
    
    enum CodingKeys: String, CodingKey {
        case username
        case avatarUrl = "avatar"
        case url
        case isLive = "is_live"
    }
}
